export { Icon, iconVariants } from "./icon"
export type { IconProps } from "./icon"

export {
  SearchIcon,
  ExploreIcon,
  ProfileIcon,
  SettingsIcon,
  NotificationIcon,
  SupportIcon,
  EditorIcon,
  StudioIcon,
  DashboardIcon,
  LibraryIcon,
  TimelineIcon,
  GlobeIcon,
  ChatIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  PlusIcon,
  CloseIcon,
  CheckIcon,
  MenuIcon,
  MoreIcon,
  ExternalLinkIcon,
  FileIcon,
  FolderIcon,
  ImageIconWrapped as ImagePlaceholderIcon,
  UploadIcon,
  DownloadIcon,
  UndoIcon,
  RedoIcon,
  BulletListIcon,
  OrderedListIcon,
  QuoteIcon as SystemQuoteIcon,
  CodeIcon,
  LinkIcon,
  ImageIcon,
  LanguagesIcon,
} from "./system"

export {
  ConceptIcon,
  ThinkerIcon,
  ArticleIcon,
  GuideIcon,
  BookIcon,
  TimelineEventIcon,
  QuoteIcon,
  CollectionIcon,
  SymbolIcon,
} from "./knowledge"

export {
  PsychologyGlyph,
  PhilosophyGlyph,
  AnthropologyGlyph,
  HistoryGlyph,
  LanguageGlyph,
  MythologyGlyph,
  ReligionGlyph,
  ScienceGlyph,
  SymbolismGlyph,
  ArtGlyph,
  AIGlyph,
  CivilizationGlyph,
} from "./domains"
