export { cn } from "./lib/utils"

export {
  Button,
  buttonVariants,
  Card,
  CardHeader,
  CardFooter,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  badgeVariants,
  Input,
  inputVariants,
  Textarea,
  Select,
  Checkbox,
  RadioGroup,
  Switch,
  switchVariants,
  thumbVariants,
  Label,
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuLabel,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
  Popover,
  PopoverTrigger,
  PopoverContent,
  Sheet,
  SheetTrigger,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
  Command,
  CommandDialog,
  CommandInput,
  CommandList,
  CommandEmpty,
  CommandGroup,
  CommandItem,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  Pagination,
  PaginationItem,
  PaginationPrevious,
  PaginationNext,
  Breadcrumbs,
  BreadcrumbItem,
  BreadcrumbSeparator,
  Tag,
  tagVariants,
  Divider,
  dividerVariants,
  Chip,
  chipVariants,
  Skeleton,
  skeletonVariants,
  Progress,
  ScrollArea,
  scrollAreaVariants,
  Collapsible,
  CollapsibleTrigger,
  CollapsibleContent,
  TOC,
  TOCItem,
  Avatar,
  AvatarImage,
  AvatarFallback,
  avatarVariants,
} from "./components/ui"

export type {
  ButtonProps,
  CardProps,
  CardHeaderProps,
  CardTitleProps,
  CardDescriptionProps,
  CardContentProps,
  CardFooterProps,
  BadgeProps,
  InputProps,
  TextareaProps,
  SelectProps,
  SelectOption,
  CheckboxProps,
  RadioGroupProps,
  RadioItem,
  SwitchProps,
  LabelProps,
  DialogProps,
  SheetProps,
  TabsProps,
  TabsListProps,
  TabsTriggerProps,
  TabsContentProps,
  PaginationProps,
  PaginationItemProps,
  PaginationNavProps,
  BreadcrumbsProps,
  BreadcrumbItemProps,
  BreadcrumbSeparatorProps,
  TagProps,
  DividerProps,
  ChipProps,
  SkeletonProps,
  ProgressProps,
  ScrollAreaProps,
  CollapsibleProps,
  CollapsibleTriggerProps,
  CollapsibleContentProps,
  TOCProps,
  TOCItemProps,
  AvatarProps,
  AvatarImageProps,
  AvatarFallbackProps,
} from "./components/ui"

export { IconBox } from "./components/icon-box"
export type { IconBoxProps } from "./components/icon-box"

export { ConceptCard, ThinkerCard, KnowledgeCard, SchoolCard, ArticleCard } from "./components/knowledge"
export type { ConceptCardProps, ThinkerCardProps, KnowledgeCardProps, SchoolCardProps, ArticleCardProps } from "./components/knowledge"

// ARCHRON Icon System (47 icons total)
export {
  // Knowledge Objects (9)
  ConceptIcon,
  ThinkerIcon,
  ArticleIcon,
  BookIcon,
  QuoteIcon,
  TimelineIcon,
  GuideIcon,
  SymbolIcon,
  CollectionIcon,
  // Domains (12)
  PsychologyIcon,
  PhilosophyIcon,
  AnthropologyIcon,
  HistoryIcon,
  LanguageIcon,
  MythologyIcon,
  ReligionIcon,
  ScienceIcon,
  SymbolismIcon,
  ArtIcon,
  AIIcon,
  CivilizationIcon,
  // Actions (20)
  SearchIcon,
  ExploreIcon,
  ConstellationIcon,
  ReadIcon,
  BookmarkIcon,
  ShareIcon,
  EditIcon,
  DeleteIcon,
  SettingsIcon,
  NotificationIcon,
  ProfileIcon,
  PlusIcon,
  CloseIcon,
  CheckIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  FilterIcon,
  SortIcon,
  MenuIcon,
  MoreIcon,
  // Status (6)
  ProgressIcon,
  CompleteIcon,
  DraftIcon,
  PublishedIcon,
  FeaturedIcon,
  ArchivedIcon,
} from "./components/icons"

export type { IconProps } from "./components/icons"
